version: '3.9'
services:
  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - my_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: catalog_db
      DB_USERNAME: root
      DB_PASSWORD: root
    command: ["sh", "-c", "wait-for-mysql.sh mysql && php artisan migrate --seed && apache2-foreground"]

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - my_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: cart_db
      DB_USERNAME: root
      DB_PASSWORD: root
    command: ["sh", "-c", "wait-for-mysql.sh mysql && php artisan migrate && apache2-foreground"]


  searchservice:
    build:
      context: ./searchservice
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - my_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: search_db
      DB_USERNAME: root
      DB_PASSWORD: root
    command: ["sh", "-c", "wait-for-mysql.sh mysql && php artisan migrate && apache2-foreground"]

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    networks:
      - my_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: orders_db
      DB_USERNAME: root
      DB_PASSWORD: root
    command: ["sh", "-c", "wait-for-mysql.sh mysql && php artisan migrate && apache2-foreground"]

  frontend:
    build:
      context: ./frontend-merchmarket
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - my_network
  
  admin:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - my_network

  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - my_network
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge