import { Product } from "./types";

export const products:Product[] = [
    {
      id: 1,
      name: "Кофта модная",
      description: "Описание модной кофты",
      link: "https://example.com/product/1",
      price: 7500,
      previousPrice: 6500,
      mainImage: "./product-picture.png",
      additionalImages: ["./product-picture.png", "./product-picture.png"],
      categories: ["Одежда и аксессуары"],
      subcategory: ["свитшоты"],
      colors: ["#FFFFFF"],
      sizes: ["m", "l"],
      gender: ["мужской", "женский"],

    },
    {
        id: 2,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 8500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Концелярия"],
        subcategory: ["свитшоты"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      },
      {
        id: 3,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["свитшоты"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 4,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
         mainImage: "./product-picture.png",
      additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        subcategory: ["худи"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 5,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["футболки"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 6,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["очки"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 7,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["очки"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 8,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["очки"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      }
      ,
      {
        id: 9,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 6500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Посуда"],
        subcategory: ["очки"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
      },{
        id: 10,
        name: "Кофта модная",
        description: "Описание модной кофты",
        link: "https://example.com/product/1",
        price: 7500,
        previousPrice: 6500,
        mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
        categories: ["Одежда и аксессуары"],
        subcategory: ["свитшоты"],
        colors: ["#FFFFFF"],
        sizes: ["m", "l"],
        gender: ["мужской", "женский"],
  
      },
      {
          id: 11,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 8500,
          previousPrice: 6500,
          mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Концелярия"],
          subcategory: ["свитшоты"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          gender: ["мужской", "женский"],
        },
        {
          id: 12,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 6500,
          previousPrice: 6500,
          mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Посуда"],
          subcategory: ["свитшоты"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          gender: ["мужской", "женский"],
        }
        ,
        {
          id: 13,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 6500,
          previousPrice: 6500,
           mainImage: "./product-picture.png",
        additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Посуда"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          subcategory: ["худи"],
          gender: ["мужской", "женский"],
        }
        ,
        {
          id: 14,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 6500,
          previousPrice: 6500,
          mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Посуда"],
          subcategory: ["футболки"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          gender: ["мужской", "женский"],
        }
        ,
        {
          id: 15,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 6500,
          previousPrice: 6500,
          mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Посуда"],
          subcategory: ["очки"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          gender: ["мужской", "женский"],
        },
        {
          id: 16,
          name: "Кофта модная",
          description: "Описание модной кофты",
          link: "https://example.com/product/1",
          price: 7500,
          previousPrice: 6500,
          mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
          categories: ["Одежда и аксессуары"],
          subcategory: ["свитшоты"],
          colors: ["#FFFFFF"],
          sizes: ["m", "l"],
          gender: ["мужской", "женский"],
    
        },
        {
            id: 17,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 8500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Концелярия"],
            subcategory: ["свитшоты"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          },
          {
            id: 18,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["свитшоты"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 19,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
             mainImage: "./product-picture.png",
          additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            subcategory: ["худи"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 20,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["футболки"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 21,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["очки"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 22,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["очки"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 23,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["очки"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          }
          ,
          {
            id: 24,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 6500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Посуда"],
            subcategory: ["очки"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
          },{
            id: 25,
            name: "Кофта модная",
            description: "Описание модной кофты",
            link: "https://example.com/product/1",
            price: 7500,
            previousPrice: 6500,
            mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
            categories: ["Одежда и аксессуары"],
            subcategory: ["свитшоты"],
            colors: ["#FFFFFF"],
            sizes: ["m", "l"],
            gender: ["мужской", "женский"],
      
          },
          {
              id: 26,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 8500,
              previousPrice: 6500,
              mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Концелярия"],
              subcategory: ["свитшоты"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              gender: ["мужской", "женский"],
            },
            {
              id: 27,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 6500,
              previousPrice: 6500,
              mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Посуда"],
              subcategory: ["свитшоты"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              gender: ["мужской", "женский"],
            }
            ,
            {
              id: 28,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 6500,
              previousPrice: 6500,
               mainImage: "./product-picture.png",
            additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Посуда"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              subcategory: ["худи"],
              gender: ["мужской", "женский"],
            }
            ,
            {
              id: 29,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 6500,
              previousPrice: 6500,
              mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Посуда"],
              subcategory: ["футболки"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              gender: ["мужской", "женский"],
            }
            ,
            {
              id: 30,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 6500,
              previousPrice: 6500,
              mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Посуда"],
              subcategory: ["очки"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              gender: ["мужской", "женский"],
            },
            {
              id: 31,
              name: "Кофта модная",
              description: "Описание модной кофты",
              link: "https://example.com/product/1",
              price: 7500,
              previousPrice: 6500,
              mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
              categories: ["Одежда и аксессуары"],
              subcategory: ["свитшоты"],
              colors: ["#FFFFFF"],
              sizes: ["m", "l"],
              gender: ["мужской", "женский"],
        
            },
            {
                id: 32,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 8500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Концелярия"],
                subcategory: ["свитшоты"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              },
              {
                id: 33,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["свитшоты"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 34,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                 mainImage: "./product-picture.png",
              additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                subcategory: ["худи"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 35,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["футболки"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 36,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["очки"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 37,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["очки"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 38,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["очки"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              }
              ,
              {
                id: 39,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 6500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Посуда"],
                subcategory: ["очки"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
              },{
                id: 40,
                name: "Кофта модная",
                description: "Описание модной кофты",
                link: "https://example.com/product/1",
                price: 7500,
                previousPrice: 6500,
                mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                categories: ["Одежда и аксессуары"],
                subcategory: ["свитшоты"],
                colors: ["#FFFFFF"],
                sizes: ["m", "l"],
                gender: ["мужской", "женский"],
          
              },
              {
                  id: 41,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 8500,
                  previousPrice: 6500,
                  mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Концелярия"],
                  subcategory: ["свитшоты"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  gender: ["мужской", "женский"],
                },
                {
                  id: 42,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 6500,
                  previousPrice: 6500,
                  mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Посуда"],
                  subcategory: ["свитшоты"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  gender: ["мужской", "женский"],
                }
                ,
                {
                  id: 43,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 6500,
                  previousPrice: 6500,
                   mainImage: "./product-picture.png",
                additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Посуда"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  subcategory: ["худи"],
                  gender: ["мужской", "женский"],
                }
                ,
                {
                  id: 44,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 6500,
                  previousPrice: 6500,
                  mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Посуда"],
                  subcategory: ["футболки"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  gender: ["мужской", "женский"],
                }
                ,
                {
                  id: 45,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 6500,
                  previousPrice: 6500,
                  mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Посуда"],
                  subcategory: ["очки"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  gender: ["мужской", "женский"],
                },    {
                  id: 46,
                  name: "Кофта модная",
                  description: "Описание модной кофты",
                  link: "https://example.com/product/1",
                  price: 7500,
                  previousPrice: 6500,
                  mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                  categories: ["Одежда и аксессуары"],
                  subcategory: ["свитшоты"],
                  colors: ["#FFFFFF"],
                  sizes: ["m", "l"],
                  gender: ["мужской", "женский"],
            
                },
                {
                    id: 47,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 8500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Концелярия"],
                    subcategory: ["свитшоты"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  },
                  {
                    id: 48,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["свитшоты"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 49,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                     mainImage: "./product-picture.png",
                  additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    subcategory: ["худи"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 50,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["футболки"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 51,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["очки"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 52,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["очки"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 53,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["очки"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  }
                  ,
                  {
                    id: 54,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 6500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Посуда"],
                    subcategory: ["очки"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
                  },{
                    id: 55,
                    name: "Кофта модная",
                    description: "Описание модной кофты",
                    link: "https://example.com/product/1",
                    price: 7500,
                    previousPrice: 6500,
                    mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                    categories: ["Одежда и аксессуары"],
                    subcategory: ["свитшоты"],
                    colors: ["#FFFFFF"],
                    sizes: ["m", "l"],
                    gender: ["мужской", "женский"],
              
                  },
                  {
                      id: 56,
                      name: "Кофта модная",
                      description: "Описание модной кофты",
                      link: "https://example.com/product/1",
                      price: 8500,
                      previousPrice: 6500,
                      mainImage: "./product-picture.png",
                      additionalImages: ["./product-picture.png", "./product-picture.png"],
                      categories: ["Концелярия"],
                      subcategory: ["свитшоты"],
                      colors: ["#FFFFFF"],
                      sizes: ["m", "l"],
                      gender: ["мужской", "женский"],
                    },
                    {
                      id: 57,
                      name: "Кофта модная",
                      description: "Описание модной кофты",
                      link: "https://example.com/product/1",
                      price: 6500,
                      previousPrice: 6500,
                      mainImage: "./product-picture.png",
                      additionalImages: ["./product-picture.png", "./product-picture.png"],
                      categories: ["Посуда"],
                      subcategory: ["свитшоты"],
                      colors: ["#FFFFFF"],
                      sizes: ["m", "l"],
                      gender: ["мужской", "женский"],
                    }
                    ,
                    {
                      id: 58,
                      name: "Кофта модная",
                      description: "Описание модной кофты",
                      link: "https://example.com/product/1",
                      price: 6500,
                      previousPrice: 6500,
                       mainImage: "./product-picture.png",
                    additionalImages: ["./product-picture.png", "./product-picture.png"],
                      categories: ["Посуда"],
                      colors: ["#FFFFFF"],
                      sizes: ["m", "l"],
                      subcategory: ["худи"],
                      gender: ["мужской", "женский"],
                    }
                    ,
                    {
                      id: 59,
                      name: "Кофта модная",
                      description: "Описание модной кофты",
                      link: "https://example.com/product/1",
                      price: 6500,
                      previousPrice: 6500,
                      mainImage: "./product-picture.png",
                      additionalImages: ["./product-picture.png", "./product-picture.png"],
                      categories: ["Посуда"],
                      subcategory: ["футболки"],
                      colors: ["#FFFFFF"],
                      sizes: ["m", "l"],
                      gender: ["мужской", "женский"],
                    }
                    ,
                    {
                      id: 60,
                      name: "Кофта модная",
                      description: "Описание модной кофты",
                      link: "https://example.com/product/1",
                      price: 6500,
                      previousPrice: 6500,
                      mainImage: "./product-picture.png",
                      additionalImages: ["./product-picture.png", "./product-picture.png"],
                      categories: ["Посуда"],
                      subcategory: ["очки"],
                      colors: ["#FFFFFF"],
                      sizes: ["m", "l"],
                      gender: ["мужской", "женский"],
                    },

  ];
  